version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: ims_postgres
    environment:
      POSTGRES_USER: ims_user
      POSTGRES_PASSWORD: ims_pass
      POSTGRES_DB: ims_db
    ports:
      - "5433:5432"

  mongodb:
    image: mongo:7
    container_name: ims_mongodb
    ports:
      - "27017:27017"

  redis:
    image: redis:7
    container_name: ims_redis
    ports:
      - "6379:6379"